### PR TITLE
Adding code in readme

### PR DESCRIPTION
**Pull request by ThreeEyedRaven3**

### CODE REVIEW

**Comment by ThreeEyedRaven3** [comment]
Hey, Maks, you could make no changes in hello-world-edit-conflict2, so i deleted your modification

**Comment by ghost** [comment]
shit, I need this modification for my new feauture that i'm developing now

**Comment by ThreeEyedRaven3** [comment]
You can modify it when the feauture will be ready. Now the project has no need to have modified "hello-world-edit-conflict2"

**Comment by ghost** [comment]
well, kk

**Pull request merged**
